runtime: python27
api_version: 1
threadsafe: false
handlers:
- url: /static
  static_dir: static
  application_readable: true

- url: /.*
  script: webapp.py
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


